### PR TITLE
Pull repo and owner from `context` getter instead of payload

### PR DESCRIPTION
**Pull request by tc4mpbell**
👋 Tl/dr
----
This pulls the `repo` and `owner` strings from the `@actions/github` `context.repo` getter, instead of `context.payload.repository`.

Why?
---
I was trying to run this with a different action (when a label is added to a PR [1]), and it was failing when trying to make a request to `"https://api.github.com/repos/undefined/my_repo/compare/master...[my sha]`. It seems like the `github.context.payload.repository.owner.name` wasn't defined for this particular action type, for whatever reason.

The `@actions/github` context source has a `repo` getter that does much the same logic, but with an additional fallback in case there's no `payload.repository`: https://github.com/actions/toolkit/blob/main/packages/github/src/context.ts#L64-L75

Switching to this usage seems to work in my tests for both action types (`on push` and `on PR label`).

----

<details>
<summary>[1] Example job YAML</summary>

```yml
name: Trello Sync

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  sync_custom_fields:
    if: ${{ github.event.label.name == 'Staging' }}
    runs-on: ubuntu-latest
    steps:
      - uses: tc4mpbell/trello-custom-field-sync-action@v0.2.4-alpha
        with:
          trello_key: ${{ secrets.TRELLO_KEY }}
          trello_token: ${{ secrets.TRELLO_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          trello_board_id: ${{ secrets.TRELLO_CALENDAR_BOARD_ID }}

```
</details>

### CODE REVIEW

**Review by kylemellander — APPROVED** [review]
Thanks for the update!

**Comment by kylemellander** [comment]
btw, I like the way you have your setup using the `if` field

**Comment by tc4mpbell** [comment]
🎉 Thanks! Don't think I have write access here, so I'll rely on you to merge/release if that's cool. 😌

**Comment by kylemellander** [comment]
I've published version 0.2.4 with this

**Pull request merged**
